version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contas_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contas_network

  # Opcional: PgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: contas_pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - contas_network

volumes:
  postgres_data:

networks:
  contas_network:
    driver: bridge
